package cr.co.sea.seaforms.DAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import cr.co.sea.seaforms.Model.Contrato;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTRATO".
*/
public class ContratoDao extends AbstractDao<Contrato, Long> {

    public static final String TABLENAME = "CONTRATO";

    /**
     * Properties of entity Contrato.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Fecha = new Property(1, java.util.Date.class, "Fecha", false, "FECHA");
        public final static Property TipoIdentificacion = new Property(2, String.class, "TipoIdentificacion", false, "TIPO_IDENTIFICACION");
        public final static Property Identificacion = new Property(3, String.class, "Identificacion", false, "IDENTIFICACION");
        public final static Property Pasaporte = new Property(4, String.class, "Pasaporte", false, "PASAPORTE");
        public final static Property Nombre = new Property(5, String.class, "Nombre", false, "NOMBRE");
        public final static Property Apellido1 = new Property(6, String.class, "Apellido1", false, "APELLIDO1");
        public final static Property Apellido2 = new Property(7, String.class, "Apellido2", false, "APELLIDO2");
        public final static Property Email = new Property(8, String.class, "Email", false, "EMAIL");
        public final static Property Sexo = new Property(9, String.class, "Sexo", false, "SEXO");
        public final static Property FechaNacimiento = new Property(10, java.util.Date.class, "FechaNacimiento", false, "FECHA_NACIMIENTO");
        public final static Property TelCasa = new Property(11, String.class, "TelCasa", false, "TEL_CASA");
        public final static Property TelCel = new Property(12, String.class, "TelCel", false, "TEL_CEL");
        public final static Property TelCel2 = new Property(13, String.class, "TelCel2", false, "TEL_CEL2");
        public final static Property Fax = new Property(14, String.class, "Fax", false, "FAX");
        public final static Property Direccion = new Property(15, String.class, "Direccion", false, "DIRECCION");
        public final static Property OtrasSenas = new Property(16, String.class, "OtrasSenas", false, "OTRAS_SENAS");
        public final static Property Provincia = new Property(17, String.class, "Provincia", false, "PROVINCIA");
        public final static Property Canton = new Property(18, String.class, "Canton", false, "CANTON");
        public final static Property Distrito = new Property(19, String.class, "Distrito", false, "DISTRITO");
        public final static Property TipoTarjeta = new Property(20, String.class, "TipoTarjeta", false, "TIPO_TARJETA");
        public final static Property NumeroTarjeta = new Property(21, String.class, "NumeroTarjeta", false, "NUMERO_TARJETA");
        public final static Property NumeroSeguridad = new Property(22, String.class, "NumeroSeguridad", false, "NUMERO_SEGURIDAD");
        public final static Property VencimientoTarjeta = new Property(23, String.class, "VencimientoTarjeta", false, "VENCIMIENTO_TARJETA");
        public final static Property MontoTotal = new Property(24, Float.class, "MontoTotal", false, "MONTO_TOTAL");
        public final static Property Foto1 = new Property(25, byte[].class, "Foto1", false, "FOTO1");
        public final static Property Foto2 = new Property(26, byte[].class, "Foto2", false, "FOTO2");
        public final static Property Foto3 = new Property(27, byte[].class, "Foto3", false, "FOTO3");
        public final static Property Foto4 = new Property(28, byte[].class, "Foto4", false, "FOTO4");
        public final static Property FotoFirma = new Property(29, byte[].class, "FotoFirma", false, "FOTO_FIRMA");
        public final static Property Generico1 = new Property(30, String.class, "Generico1", false, "GENERICO1");
        public final static Property Generico2 = new Property(31, String.class, "Generico2", false, "GENERICO2");
        public final static Property Generico3 = new Property(32, String.class, "Generico3", false, "GENERICO3");
        public final static Property Generico4 = new Property(33, String.class, "Generico4", false, "GENERICO4");
        public final static Property Generico5 = new Property(34, String.class, "Generico5", false, "GENERICO5");
        public final static Property Generico6 = new Property(35, String.class, "Generico6", false, "GENERICO6");
        public final static Property Generico7 = new Property(36, String.class, "Generico7", false, "GENERICO7");
        public final static Property Generico8 = new Property(37, String.class, "Generico8", false, "GENERICO8");
        public final static Property Generico9 = new Property(38, String.class, "Generico9", false, "GENERICO9");
        public final static Property Generico10 = new Property(39, String.class, "Generico10", false, "GENERICO10");
        public final static Property Generico11 = new Property(40, String.class, "Generico11", false, "GENERICO11");
        public final static Property Generico12 = new Property(41, String.class, "Generico12", false, "GENERICO12");
        public final static Property Generico13 = new Property(42, String.class, "Generico13", false, "GENERICO13");
        public final static Property Generico14 = new Property(43, String.class, "Generico14", false, "GENERICO14");
        public final static Property Generico15 = new Property(44, String.class, "Generico15", false, "GENERICO15");
        public final static Property Generico16 = new Property(45, String.class, "Generico16", false, "GENERICO16");
        public final static Property Generico17 = new Property(46, String.class, "Generico17", false, "GENERICO17");
        public final static Property Generico18 = new Property(47, String.class, "Generico18", false, "GENERICO18");
        public final static Property Generico19 = new Property(48, String.class, "Generico19", false, "GENERICO19");
        public final static Property Generico20 = new Property(49, String.class, "Generico20", false, "GENERICO20");
        public final static Property Generico21 = new Property(50, String.class, "Generico21", false, "GENERICO21");
        public final static Property Generico22 = new Property(51, String.class, "Generico22", false, "GENERICO22");
        public final static Property Generico23 = new Property(52, String.class, "Generico23", false, "GENERICO23");
        public final static Property Generico24 = new Property(53, String.class, "Generico24", false, "GENERICO24");
        public final static Property Generico25 = new Property(54, String.class, "Generico25", false, "GENERICO25");
        public final static Property Generico26 = new Property(55, String.class, "Generico26", false, "GENERICO26");
        public final static Property Generico27 = new Property(56, String.class, "Generico27", false, "GENERICO27");
        public final static Property Generico28 = new Property(57, String.class, "Generico28", false, "GENERICO28");
        public final static Property Generico29 = new Property(58, String.class, "Generico29", false, "GENERICO29");
        public final static Property Generico30 = new Property(59, String.class, "Generico30", false, "GENERICO30");
    };


    public ContratoDao(DaoConfig config) {
        super(config);
    }
    
    public ContratoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTRATO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FECHA\" INTEGER," + // 1: Fecha
                "\"TIPO_IDENTIFICACION\" TEXT," + // 2: TipoIdentificacion
                "\"IDENTIFICACION\" TEXT," + // 3: Identificacion
                "\"PASAPORTE\" TEXT," + // 4: Pasaporte
                "\"NOMBRE\" TEXT NOT NULL ," + // 5: Nombre
                "\"APELLIDO1\" TEXT NOT NULL ," + // 6: Apellido1
                "\"APELLIDO2\" TEXT," + // 7: Apellido2
                "\"EMAIL\" TEXT," + // 8: Email
                "\"SEXO\" TEXT NOT NULL ," + // 9: Sexo
                "\"FECHA_NACIMIENTO\" INTEGER NOT NULL ," + // 10: FechaNacimiento
                "\"TEL_CASA\" TEXT," + // 11: TelCasa
                "\"TEL_CEL\" TEXT," + // 12: TelCel
                "\"TEL_CEL2\" TEXT," + // 13: TelCel2
                "\"FAX\" TEXT," + // 14: Fax
                "\"DIRECCION\" TEXT NOT NULL ," + // 15: Direccion
                "\"OTRAS_SENAS\" TEXT," + // 16: OtrasSenas
                "\"PROVINCIA\" TEXT," + // 17: Provincia
                "\"CANTON\" TEXT," + // 18: Canton
                "\"DISTRITO\" TEXT," + // 19: Distrito
                "\"TIPO_TARJETA\" TEXT," + // 20: TipoTarjeta
                "\"NUMERO_TARJETA\" TEXT," + // 21: NumeroTarjeta
                "\"NUMERO_SEGURIDAD\" TEXT," + // 22: NumeroSeguridad
                "\"VENCIMIENTO_TARJETA\" TEXT," + // 23: VencimientoTarjeta
                "\"MONTO_TOTAL\" REAL," + // 24: MontoTotal
                "\"FOTO1\" BLOB," + // 25: Foto1
                "\"FOTO2\" BLOB," + // 26: Foto2
                "\"FOTO3\" BLOB," + // 27: Foto3
                "\"FOTO4\" BLOB," + // 28: Foto4
                "\"FOTO_FIRMA\" BLOB," + // 29: FotoFirma
                "\"GENERICO1\" TEXT," + // 30: Generico1
                "\"GENERICO2\" TEXT," + // 31: Generico2
                "\"GENERICO3\" TEXT," + // 32: Generico3
                "\"GENERICO4\" TEXT," + // 33: Generico4
                "\"GENERICO5\" TEXT," + // 34: Generico5
                "\"GENERICO6\" TEXT," + // 35: Generico6
                "\"GENERICO7\" TEXT," + // 36: Generico7
                "\"GENERICO8\" TEXT," + // 37: Generico8
                "\"GENERICO9\" TEXT," + // 38: Generico9
                "\"GENERICO10\" TEXT," + // 39: Generico10
                "\"GENERICO11\" TEXT," + // 40: Generico11
                "\"GENERICO12\" TEXT," + // 41: Generico12
                "\"GENERICO13\" TEXT," + // 42: Generico13
                "\"GENERICO14\" TEXT," + // 43: Generico14
                "\"GENERICO15\" TEXT," + // 44: Generico15
                "\"GENERICO16\" TEXT," + // 45: Generico16
                "\"GENERICO17\" TEXT," + // 46: Generico17
                "\"GENERICO18\" TEXT," + // 47: Generico18
                "\"GENERICO19\" TEXT," + // 48: Generico19
                "\"GENERICO20\" TEXT," + // 49: Generico20
                "\"GENERICO21\" TEXT," + // 50: Generico21
                "\"GENERICO22\" TEXT," + // 51: Generico22
                "\"GENERICO23\" TEXT," + // 52: Generico23
                "\"GENERICO24\" TEXT," + // 53: Generico24
                "\"GENERICO25\" TEXT," + // 54: Generico25
                "\"GENERICO26\" TEXT," + // 55: Generico26
                "\"GENERICO27\" TEXT," + // 56: Generico27
                "\"GENERICO28\" TEXT," + // 57: Generico28
                "\"GENERICO29\" TEXT," + // 58: Generico29
                "\"GENERICO30\" TEXT);"); // 59: Generico30
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTRATO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Contrato entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date Fecha = entity.getFecha();
        if (Fecha != null) {
            stmt.bindLong(2, Fecha.getTime());
        }
 
        String TipoIdentificacion = entity.getTipoIdentificacion();
        if (TipoIdentificacion != null) {
            stmt.bindString(3, TipoIdentificacion);
        }
 
        String Identificacion = entity.getIdentificacion();
        if (Identificacion != null) {
            stmt.bindString(4, Identificacion);
        }
 
        String Pasaporte = entity.getPasaporte();
        if (Pasaporte != null) {
            stmt.bindString(5, Pasaporte);
        }
        stmt.bindString(6, entity.getNombre());
        stmt.bindString(7, entity.getApellido1());
 
        String Apellido2 = entity.getApellido2();
        if (Apellido2 != null) {
            stmt.bindString(8, Apellido2);
        }
 
        String Email = entity.getEmail();
        if (Email != null) {
            stmt.bindString(9, Email);
        }
        stmt.bindString(10, entity.getSexo());
        stmt.bindLong(11, entity.getFechaNacimiento().getTime());
 
        String TelCasa = entity.getTelCasa();
        if (TelCasa != null) {
            stmt.bindString(12, TelCasa);
        }
 
        String TelCel = entity.getTelCel();
        if (TelCel != null) {
            stmt.bindString(13, TelCel);
        }
 
        String TelCel2 = entity.getTelCel2();
        if (TelCel2 != null) {
            stmt.bindString(14, TelCel2);
        }
 
        String Fax = entity.getFax();
        if (Fax != null) {
            stmt.bindString(15, Fax);
        }
        stmt.bindString(16, entity.getDireccion());
 
        String OtrasSenas = entity.getOtrasSenas();
        if (OtrasSenas != null) {
            stmt.bindString(17, OtrasSenas);
        }
 
        String Provincia = entity.getProvincia();
        if (Provincia != null) {
            stmt.bindString(18, Provincia);
        }
 
        String Canton = entity.getCanton();
        if (Canton != null) {
            stmt.bindString(19, Canton);
        }
 
        String Distrito = entity.getDistrito();
        if (Distrito != null) {
            stmt.bindString(20, Distrito);
        }
 
        String TipoTarjeta = entity.getTipoTarjeta();
        if (TipoTarjeta != null) {
            stmt.bindString(21, TipoTarjeta);
        }
 
        String NumeroTarjeta = entity.getNumeroTarjeta();
        if (NumeroTarjeta != null) {
            stmt.bindString(22, NumeroTarjeta);
        }
 
        String NumeroSeguridad = entity.getNumeroSeguridad();
        if (NumeroSeguridad != null) {
            stmt.bindString(23, NumeroSeguridad);
        }
 
        String VencimientoTarjeta = entity.getVencimientoTarjeta();
        if (VencimientoTarjeta != null) {
            stmt.bindString(24, VencimientoTarjeta);
        }
 
        Float MontoTotal = entity.getMontoTotal();
        if (MontoTotal != null) {
            stmt.bindDouble(25, MontoTotal);
        }
 
        byte[] Foto1 = entity.getFoto1();
        if (Foto1 != null) {
            stmt.bindBlob(26, Foto1);
        }
 
        byte[] Foto2 = entity.getFoto2();
        if (Foto2 != null) {
            stmt.bindBlob(27, Foto2);
        }
 
        byte[] Foto3 = entity.getFoto3();
        if (Foto3 != null) {
            stmt.bindBlob(28, Foto3);
        }
 
        byte[] Foto4 = entity.getFoto4();
        if (Foto4 != null) {
            stmt.bindBlob(29, Foto4);
        }
 
        byte[] FotoFirma = entity.getFotoFirma();
        if (FotoFirma != null) {
            stmt.bindBlob(30, FotoFirma);
        }
 
        String Generico1 = entity.getGenerico1();
        if (Generico1 != null) {
            stmt.bindString(31, Generico1);
        }
 
        String Generico2 = entity.getGenerico2();
        if (Generico2 != null) {
            stmt.bindString(32, Generico2);
        }
 
        String Generico3 = entity.getGenerico3();
        if (Generico3 != null) {
            stmt.bindString(33, Generico3);
        }
 
        String Generico4 = entity.getGenerico4();
        if (Generico4 != null) {
            stmt.bindString(34, Generico4);
        }
 
        String Generico5 = entity.getGenerico5();
        if (Generico5 != null) {
            stmt.bindString(35, Generico5);
        }
 
        String Generico6 = entity.getGenerico6();
        if (Generico6 != null) {
            stmt.bindString(36, Generico6);
        }
 
        String Generico7 = entity.getGenerico7();
        if (Generico7 != null) {
            stmt.bindString(37, Generico7);
        }
 
        String Generico8 = entity.getGenerico8();
        if (Generico8 != null) {
            stmt.bindString(38, Generico8);
        }
 
        String Generico9 = entity.getGenerico9();
        if (Generico9 != null) {
            stmt.bindString(39, Generico9);
        }
 
        String Generico10 = entity.getGenerico10();
        if (Generico10 != null) {
            stmt.bindString(40, Generico10);
        }
 
        String Generico11 = entity.getGenerico11();
        if (Generico11 != null) {
            stmt.bindString(41, Generico11);
        }
 
        String Generico12 = entity.getGenerico12();
        if (Generico12 != null) {
            stmt.bindString(42, Generico12);
        }
 
        String Generico13 = entity.getGenerico13();
        if (Generico13 != null) {
            stmt.bindString(43, Generico13);
        }
 
        String Generico14 = entity.getGenerico14();
        if (Generico14 != null) {
            stmt.bindString(44, Generico14);
        }
 
        String Generico15 = entity.getGenerico15();
        if (Generico15 != null) {
            stmt.bindString(45, Generico15);
        }
 
        String Generico16 = entity.getGenerico16();
        if (Generico16 != null) {
            stmt.bindString(46, Generico16);
        }
 
        String Generico17 = entity.getGenerico17();
        if (Generico17 != null) {
            stmt.bindString(47, Generico17);
        }
 
        String Generico18 = entity.getGenerico18();
        if (Generico18 != null) {
            stmt.bindString(48, Generico18);
        }
 
        String Generico19 = entity.getGenerico19();
        if (Generico19 != null) {
            stmt.bindString(49, Generico19);
        }
 
        String Generico20 = entity.getGenerico20();
        if (Generico20 != null) {
            stmt.bindString(50, Generico20);
        }
 
        String Generico21 = entity.getGenerico21();
        if (Generico21 != null) {
            stmt.bindString(51, Generico21);
        }
 
        String Generico22 = entity.getGenerico22();
        if (Generico22 != null) {
            stmt.bindString(52, Generico22);
        }
 
        String Generico23 = entity.getGenerico23();
        if (Generico23 != null) {
            stmt.bindString(53, Generico23);
        }
 
        String Generico24 = entity.getGenerico24();
        if (Generico24 != null) {
            stmt.bindString(54, Generico24);
        }
 
        String Generico25 = entity.getGenerico25();
        if (Generico25 != null) {
            stmt.bindString(55, Generico25);
        }
 
        String Generico26 = entity.getGenerico26();
        if (Generico26 != null) {
            stmt.bindString(56, Generico26);
        }
 
        String Generico27 = entity.getGenerico27();
        if (Generico27 != null) {
            stmt.bindString(57, Generico27);
        }
 
        String Generico28 = entity.getGenerico28();
        if (Generico28 != null) {
            stmt.bindString(58, Generico28);
        }
 
        String Generico29 = entity.getGenerico29();
        if (Generico29 != null) {
            stmt.bindString(59, Generico29);
        }
 
        String Generico30 = entity.getGenerico30();
        if (Generico30 != null) {
            stmt.bindString(60, Generico30);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Contrato readEntity(Cursor cursor, int offset) {
        Contrato entity = new Contrato( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // Fecha
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // TipoIdentificacion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Identificacion
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Pasaporte
            cursor.getString(offset + 5), // Nombre
            cursor.getString(offset + 6), // Apellido1
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Apellido2
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // Email
            cursor.getString(offset + 9), // Sexo
            new java.util.Date(cursor.getLong(offset + 10)), // FechaNacimiento
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // TelCasa
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // TelCel
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // TelCel2
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // Fax
            cursor.getString(offset + 15), // Direccion
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // OtrasSenas
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // Provincia
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // Canton
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // Distrito
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // TipoTarjeta
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // NumeroTarjeta
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // NumeroSeguridad
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // VencimientoTarjeta
            cursor.isNull(offset + 24) ? null : cursor.getFloat(offset + 24), // MontoTotal
            cursor.isNull(offset + 25) ? null : cursor.getBlob(offset + 25), // Foto1
            cursor.isNull(offset + 26) ? null : cursor.getBlob(offset + 26), // Foto2
            cursor.isNull(offset + 27) ? null : cursor.getBlob(offset + 27), // Foto3
            cursor.isNull(offset + 28) ? null : cursor.getBlob(offset + 28), // Foto4
            cursor.isNull(offset + 29) ? null : cursor.getBlob(offset + 29), // FotoFirma
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // Generico1
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // Generico2
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // Generico3
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // Generico4
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // Generico5
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // Generico6
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // Generico7
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // Generico8
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // Generico9
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // Generico10
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // Generico11
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // Generico12
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // Generico13
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // Generico14
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // Generico15
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // Generico16
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // Generico17
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // Generico18
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // Generico19
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // Generico20
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // Generico21
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // Generico22
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // Generico23
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // Generico24
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // Generico25
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // Generico26
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // Generico27
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // Generico28
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // Generico29
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59) // Generico30
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Contrato entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFecha(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setTipoIdentificacion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdentificacion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPasaporte(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNombre(cursor.getString(offset + 5));
        entity.setApellido1(cursor.getString(offset + 6));
        entity.setApellido2(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEmail(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSexo(cursor.getString(offset + 9));
        entity.setFechaNacimiento(new java.util.Date(cursor.getLong(offset + 10)));
        entity.setTelCasa(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTelCel(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTelCel2(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setFax(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setDireccion(cursor.getString(offset + 15));
        entity.setOtrasSenas(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setProvincia(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setCanton(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setDistrito(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTipoTarjeta(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setNumeroTarjeta(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setNumeroSeguridad(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setVencimientoTarjeta(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setMontoTotal(cursor.isNull(offset + 24) ? null : cursor.getFloat(offset + 24));
        entity.setFoto1(cursor.isNull(offset + 25) ? null : cursor.getBlob(offset + 25));
        entity.setFoto2(cursor.isNull(offset + 26) ? null : cursor.getBlob(offset + 26));
        entity.setFoto3(cursor.isNull(offset + 27) ? null : cursor.getBlob(offset + 27));
        entity.setFoto4(cursor.isNull(offset + 28) ? null : cursor.getBlob(offset + 28));
        entity.setFotoFirma(cursor.isNull(offset + 29) ? null : cursor.getBlob(offset + 29));
        entity.setGenerico1(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setGenerico2(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setGenerico3(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setGenerico4(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setGenerico5(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setGenerico6(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setGenerico7(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setGenerico8(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setGenerico9(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setGenerico10(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setGenerico11(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setGenerico12(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setGenerico13(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setGenerico14(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setGenerico15(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setGenerico16(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setGenerico17(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setGenerico18(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setGenerico19(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setGenerico20(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setGenerico21(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setGenerico22(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setGenerico23(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setGenerico24(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setGenerico25(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setGenerico26(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setGenerico27(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setGenerico28(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setGenerico29(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setGenerico30(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Contrato entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Contrato entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
