package cr.co.sea.seaforms.DAO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import cr.co.sea.seaforms.Model.Contrato;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cr.co.sea.seaforms.Model.Cliente;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clienteDaoConfig;
    private final DaoConfig contratoDaoConfig;

    private final ClienteDao clienteDao;
    private final ContratoDao contratoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        contratoDaoConfig = daoConfigMap.get(ContratoDao.class).clone();
        contratoDaoConfig.initIdentityScope(type);

        clienteDao = new ClienteDao(clienteDaoConfig, this);
        contratoDao = new ContratoDao(contratoDaoConfig, this);

        registerDao(Cliente.class, clienteDao);
        registerDao(Contrato.class, contratoDao);
    }
    
    public void clear() {
        clienteDaoConfig.getIdentityScope().clear();
        contratoDaoConfig.getIdentityScope().clear();
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public ContratoDao getContratoDao() {
        return contratoDao;
    }

}
