package cr.co.sea.seaforms.Model;

import java.util.List;

import cr.co.sea.seaforms.DAO.ClienteDao;
import cr.co.sea.seaforms.DAO.ContratoDao;
import cr.co.sea.seaforms.DAO.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CLIENTE".
 */
public class Cliente {

    private Long id;
    private String CliTipoIdentificacion;
    private String CliIdentificacion;
    private String CliPasaporte;
    /** Not-null value. */
    private String CliNombre;
    /** Not-null value. */
    private String CliApellido1;
    private String CliApellido2;
    private String CliEmail;
    /** Not-null value. */
    private String CliSexo;
    /** Not-null value. */
    private java.util.Date CliFechaNacimiento;
    private String CliTelCasa;
    private String CliTelCel;
    private String CliTelCel2;
    private String CliFax;
    /** Not-null value. */
    private String CliDireccion;
    private String CliOtrasSenas;
    private String CliProvincia;
    private String CliCanton;
    private String CliDistrito;
    private String CliTipoTarjeta;
    private String CliNumeroTarjeta;
    private String CliNumeroSeguridad;
    private String CliVencimientoTarjeta;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ClienteDao myDao;

    private List<Contrato> cliContratos;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    static Cliente clienteSingleton;
    public Cliente() {
    }

    public Cliente(Long id) {
        this.id = id;
    }

    public Cliente(Long id, String CliTipoIdentificacion, String CliIdentificacion, String CliPasaporte, String CliNombre, String CliApellido1, String CliApellido2, String CliEmail, String CliSexo, java.util.Date CliFechaNacimiento, String CliTelCasa, String CliTelCel, String CliTelCel2, String CliFax, String CliDireccion, String CliOtrasSenas, String CliProvincia, String CliCanton, String CliDistrito, String CliTipoTarjeta, String CliNumeroTarjeta, String CliNumeroSeguridad, String CliVencimientoTarjeta) {
        this.id = id;
        this.CliTipoIdentificacion = CliTipoIdentificacion;
        this.CliIdentificacion = CliIdentificacion;
        this.CliPasaporte = CliPasaporte;
        this.CliNombre = CliNombre;
        this.CliApellido1 = CliApellido1;
        this.CliApellido2 = CliApellido2;
        this.CliEmail = CliEmail;
        this.CliSexo = CliSexo;
        this.CliFechaNacimiento = CliFechaNacimiento;
        this.CliTelCasa = CliTelCasa;
        this.CliTelCel = CliTelCel;
        this.CliTelCel2 = CliTelCel2;
        this.CliFax = CliFax;
        this.CliDireccion = CliDireccion;
        this.CliOtrasSenas = CliOtrasSenas;
        this.CliProvincia = CliProvincia;
        this.CliCanton = CliCanton;
        this.CliDistrito = CliDistrito;
        this.CliTipoTarjeta = CliTipoTarjeta;
        this.CliNumeroTarjeta = CliNumeroTarjeta;
        this.CliNumeroSeguridad = CliNumeroSeguridad;
        this.CliVencimientoTarjeta = CliVencimientoTarjeta;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getClienteDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCliTipoIdentificacion() {
        return CliTipoIdentificacion;
    }

    public void setCliTipoIdentificacion(String CliTipoIdentificacion) {
        this.CliTipoIdentificacion = CliTipoIdentificacion;
    }

    public String getCliIdentificacion() {
        return CliIdentificacion;
    }

    public void setCliIdentificacion(String CliIdentificacion) {
        this.CliIdentificacion = CliIdentificacion;
    }

    public String getCliPasaporte() {
        return CliPasaporte;
    }

    public void setCliPasaporte(String CliPasaporte) {
        this.CliPasaporte = CliPasaporte;
    }

    /** Not-null value. */
    public String getCliNombre() {
        return CliNombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCliNombre(String CliNombre) {
        this.CliNombre = CliNombre;
    }

    /** Not-null value. */
    public String getCliApellido1() {
        return CliApellido1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCliApellido1(String CliApellido1) {
        this.CliApellido1 = CliApellido1;
    }

    public String getCliApellido2() {
        return CliApellido2;
    }

    public void setCliApellido2(String CliApellido2) {
        this.CliApellido2 = CliApellido2;
    }

    public String getCliEmail() {
        return CliEmail;
    }

    public void setCliEmail(String CliEmail) {
        this.CliEmail = CliEmail;
    }

    /** Not-null value. */
    public String getCliSexo() {
        return CliSexo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCliSexo(String CliSexo) {
        this.CliSexo = CliSexo;
    }

    /** Not-null value. */
    public java.util.Date getCliFechaNacimiento() {
        return CliFechaNacimiento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCliFechaNacimiento(java.util.Date CliFechaNacimiento) {
        this.CliFechaNacimiento = CliFechaNacimiento;
    }

    public String getCliTelCasa() {
        return CliTelCasa;
    }

    public void setCliTelCasa(String CliTelCasa) {
        this.CliTelCasa = CliTelCasa;
    }

    public String getCliTelCel() {
        return CliTelCel;
    }

    public void setCliTelCel(String CliTelCel) {
        this.CliTelCel = CliTelCel;
    }

    public String getCliTelCel2() {
        return CliTelCel2;
    }

    public void setCliTelCel2(String CliTelCel2) {
        this.CliTelCel2 = CliTelCel2;
    }

    public String getCliFax() {
        return CliFax;
    }

    public void setCliFax(String CliFax) {
        this.CliFax = CliFax;
    }

    /** Not-null value. */
    public String getCliDireccion() {
        return CliDireccion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCliDireccion(String CliDireccion) {
        this.CliDireccion = CliDireccion;
    }

    public String getCliOtrasSenas() {
        return CliOtrasSenas;
    }

    public void setCliOtrasSenas(String CliOtrasSenas) {
        this.CliOtrasSenas = CliOtrasSenas;
    }

    public String getCliProvincia() {
        return CliProvincia;
    }

    public void setCliProvincia(String CliProvincia) {
        this.CliProvincia = CliProvincia;
    }

    public String getCliCanton() {
        return CliCanton;
    }

    public void setCliCanton(String CliCanton) {
        this.CliCanton = CliCanton;
    }

    public String getCliDistrito() {
        return CliDistrito;
    }

    public void setCliDistrito(String CliDistrito) {
        this.CliDistrito = CliDistrito;
    }

    public String getCliTipoTarjeta() {
        return CliTipoTarjeta;
    }

    public void setCliTipoTarjeta(String CliTipoTarjeta) {
        this.CliTipoTarjeta = CliTipoTarjeta;
    }

    public String getCliNumeroTarjeta() {
        return CliNumeroTarjeta;
    }

    public void setCliNumeroTarjeta(String CliNumeroTarjeta) {
        this.CliNumeroTarjeta = CliNumeroTarjeta;
    }

    public String getCliNumeroSeguridad() {
        return CliNumeroSeguridad;
    }

    public void setCliNumeroSeguridad(String CliNumeroSeguridad) {
        this.CliNumeroSeguridad = CliNumeroSeguridad;
    }

    public String getCliVencimientoTarjeta() {
        return CliVencimientoTarjeta;
    }

    public void setCliVencimientoTarjeta(String CliVencimientoTarjeta) {
        this.CliVencimientoTarjeta = CliVencimientoTarjeta;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Contrato> getCliContratos() {
        if (cliContratos == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ContratoDao targetDao = daoSession.getContratoDao();
            List<Contrato> cliContratosNew = targetDao._queryCliente_CliContratos(id);
            synchronized (this) {
                if(cliContratos == null) {
                    cliContratos = cliContratosNew;
                }
            }
        }
        return cliContratos;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetCliContratos() {
        cliContratos = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public static Cliente getClienteSingleton() {
        if(clienteSingleton == null){
            clienteSingleton = new Cliente();
        }
        return clienteSingleton;
    }
}
