package cr.co.sea.seaforms.Model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONTRATO".
 */
public class Contrato {

    private Long id;
    private java.util.Date ConFecha;
    private String ConGenerico1;
    private String ConGenerico2;
    private String ConGenerico3;
    private String ConGenerico4;
    private String ConGenerico5;
    private String ConGenerico6;
    private String ConGenerico7;
    private String ConGenerico8;
    private String ConGenerico9;
    private String ConGenerico10;
    private String ConGenerico11;
    private String ConGenerico12;
    private String ConGenerico13;
    private String ConGenerico14;
    private String ConGenerico15;
    private String ConGenerico16;
    private String ConGenerico17;
    private String ConGenerico18;
    private String ConGenerico19;
    private String ConGenerico20;
    private String ConGenerico21;
    private String ConGenerico22;
    private String ConGenerico23;
    private String ConGenerico24;
    private String ConGenerico25;
    private String ConGenerico26;
    private String ConGenerico27;
    private String ConGenerico28;
    private String ConGenerico29;
    private String ConGenerico30;
    private long CliId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Contrato() {
    }

    public Contrato(Long id) {
        this.id = id;
    }

    public Contrato(Long id, java.util.Date ConFecha, String ConGenerico1, String ConGenerico2, String ConGenerico3, String ConGenerico4, String ConGenerico5, String ConGenerico6, String ConGenerico7, String ConGenerico8, String ConGenerico9, String ConGenerico10, String ConGenerico11, String ConGenerico12, String ConGenerico13, String ConGenerico14, String ConGenerico15, String ConGenerico16, String ConGenerico17, String ConGenerico18, String ConGenerico19, String ConGenerico20, String ConGenerico21, String ConGenerico22, String ConGenerico23, String ConGenerico24, String ConGenerico25, String ConGenerico26, String ConGenerico27, String ConGenerico28, String ConGenerico29, String ConGenerico30, long CliId) {
        this.id = id;
        this.ConFecha = ConFecha;
        this.ConGenerico1 = ConGenerico1;
        this.ConGenerico2 = ConGenerico2;
        this.ConGenerico3 = ConGenerico3;
        this.ConGenerico4 = ConGenerico4;
        this.ConGenerico5 = ConGenerico5;
        this.ConGenerico6 = ConGenerico6;
        this.ConGenerico7 = ConGenerico7;
        this.ConGenerico8 = ConGenerico8;
        this.ConGenerico9 = ConGenerico9;
        this.ConGenerico10 = ConGenerico10;
        this.ConGenerico11 = ConGenerico11;
        this.ConGenerico12 = ConGenerico12;
        this.ConGenerico13 = ConGenerico13;
        this.ConGenerico14 = ConGenerico14;
        this.ConGenerico15 = ConGenerico15;
        this.ConGenerico16 = ConGenerico16;
        this.ConGenerico17 = ConGenerico17;
        this.ConGenerico18 = ConGenerico18;
        this.ConGenerico19 = ConGenerico19;
        this.ConGenerico20 = ConGenerico20;
        this.ConGenerico21 = ConGenerico21;
        this.ConGenerico22 = ConGenerico22;
        this.ConGenerico23 = ConGenerico23;
        this.ConGenerico24 = ConGenerico24;
        this.ConGenerico25 = ConGenerico25;
        this.ConGenerico26 = ConGenerico26;
        this.ConGenerico27 = ConGenerico27;
        this.ConGenerico28 = ConGenerico28;
        this.ConGenerico29 = ConGenerico29;
        this.ConGenerico30 = ConGenerico30;
        this.CliId = CliId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getConFecha() {
        return ConFecha;
    }

    public void setConFecha(java.util.Date ConFecha) {
        this.ConFecha = ConFecha;
    }

    public String getConGenerico1() {
        return ConGenerico1;
    }

    public void setConGenerico1(String ConGenerico1) {
        this.ConGenerico1 = ConGenerico1;
    }

    public String getConGenerico2() {
        return ConGenerico2;
    }

    public void setConGenerico2(String ConGenerico2) {
        this.ConGenerico2 = ConGenerico2;
    }

    public String getConGenerico3() {
        return ConGenerico3;
    }

    public void setConGenerico3(String ConGenerico3) {
        this.ConGenerico3 = ConGenerico3;
    }

    public String getConGenerico4() {
        return ConGenerico4;
    }

    public void setConGenerico4(String ConGenerico4) {
        this.ConGenerico4 = ConGenerico4;
    }

    public String getConGenerico5() {
        return ConGenerico5;
    }

    public void setConGenerico5(String ConGenerico5) {
        this.ConGenerico5 = ConGenerico5;
    }

    public String getConGenerico6() {
        return ConGenerico6;
    }

    public void setConGenerico6(String ConGenerico6) {
        this.ConGenerico6 = ConGenerico6;
    }

    public String getConGenerico7() {
        return ConGenerico7;
    }

    public void setConGenerico7(String ConGenerico7) {
        this.ConGenerico7 = ConGenerico7;
    }

    public String getConGenerico8() {
        return ConGenerico8;
    }

    public void setConGenerico8(String ConGenerico8) {
        this.ConGenerico8 = ConGenerico8;
    }

    public String getConGenerico9() {
        return ConGenerico9;
    }

    public void setConGenerico9(String ConGenerico9) {
        this.ConGenerico9 = ConGenerico9;
    }

    public String getConGenerico10() {
        return ConGenerico10;
    }

    public void setConGenerico10(String ConGenerico10) {
        this.ConGenerico10 = ConGenerico10;
    }

    public String getConGenerico11() {
        return ConGenerico11;
    }

    public void setConGenerico11(String ConGenerico11) {
        this.ConGenerico11 = ConGenerico11;
    }

    public String getConGenerico12() {
        return ConGenerico12;
    }

    public void setConGenerico12(String ConGenerico12) {
        this.ConGenerico12 = ConGenerico12;
    }

    public String getConGenerico13() {
        return ConGenerico13;
    }

    public void setConGenerico13(String ConGenerico13) {
        this.ConGenerico13 = ConGenerico13;
    }

    public String getConGenerico14() {
        return ConGenerico14;
    }

    public void setConGenerico14(String ConGenerico14) {
        this.ConGenerico14 = ConGenerico14;
    }

    public String getConGenerico15() {
        return ConGenerico15;
    }

    public void setConGenerico15(String ConGenerico15) {
        this.ConGenerico15 = ConGenerico15;
    }

    public String getConGenerico16() {
        return ConGenerico16;
    }

    public void setConGenerico16(String ConGenerico16) {
        this.ConGenerico16 = ConGenerico16;
    }

    public String getConGenerico17() {
        return ConGenerico17;
    }

    public void setConGenerico17(String ConGenerico17) {
        this.ConGenerico17 = ConGenerico17;
    }

    public String getConGenerico18() {
        return ConGenerico18;
    }

    public void setConGenerico18(String ConGenerico18) {
        this.ConGenerico18 = ConGenerico18;
    }

    public String getConGenerico19() {
        return ConGenerico19;
    }

    public void setConGenerico19(String ConGenerico19) {
        this.ConGenerico19 = ConGenerico19;
    }

    public String getConGenerico20() {
        return ConGenerico20;
    }

    public void setConGenerico20(String ConGenerico20) {
        this.ConGenerico20 = ConGenerico20;
    }

    public String getConGenerico21() {
        return ConGenerico21;
    }

    public void setConGenerico21(String ConGenerico21) {
        this.ConGenerico21 = ConGenerico21;
    }

    public String getConGenerico22() {
        return ConGenerico22;
    }

    public void setConGenerico22(String ConGenerico22) {
        this.ConGenerico22 = ConGenerico22;
    }

    public String getConGenerico23() {
        return ConGenerico23;
    }

    public void setConGenerico23(String ConGenerico23) {
        this.ConGenerico23 = ConGenerico23;
    }

    public String getConGenerico24() {
        return ConGenerico24;
    }

    public void setConGenerico24(String ConGenerico24) {
        this.ConGenerico24 = ConGenerico24;
    }

    public String getConGenerico25() {
        return ConGenerico25;
    }

    public void setConGenerico25(String ConGenerico25) {
        this.ConGenerico25 = ConGenerico25;
    }

    public String getConGenerico26() {
        return ConGenerico26;
    }

    public void setConGenerico26(String ConGenerico26) {
        this.ConGenerico26 = ConGenerico26;
    }

    public String getConGenerico27() {
        return ConGenerico27;
    }

    public void setConGenerico27(String ConGenerico27) {
        this.ConGenerico27 = ConGenerico27;
    }

    public String getConGenerico28() {
        return ConGenerico28;
    }

    public void setConGenerico28(String ConGenerico28) {
        this.ConGenerico28 = ConGenerico28;
    }

    public String getConGenerico29() {
        return ConGenerico29;
    }

    public void setConGenerico29(String ConGenerico29) {
        this.ConGenerico29 = ConGenerico29;
    }

    public String getConGenerico30() {
        return ConGenerico30;
    }

    public void setConGenerico30(String ConGenerico30) {
        this.ConGenerico30 = ConGenerico30;
    }

    public long getCliId() {
        return CliId;
    }

    public void setCliId(long CliId) {
        this.CliId = CliId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
