package cr.co.sea.seaforms.Model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONTRATO".
 */
public class Contrato {

    private Long id;
    private java.util.Date Fecha;
    private String TipoIdentificacion;
    private String Identificacion;
    private String Pasaporte;
    /** Not-null value. */
    private String Nombre;
    /** Not-null value. */
    private String Apellido1;
    private String Apellido2;
    private String Email;
    /** Not-null value. */
    private String Sexo;
    /** Not-null value. */
    private java.util.Date FechaNacimiento;
    private String TelCasa;
    private String TelCel;
    private String TelCel2;
    private String Fax;
    /** Not-null value. */
    private String Direccion;
    private String OtrasSenas;
    private String Provincia;
    private String Canton;
    private String Distrito;
    private String TipoTarjeta;
    private String NumeroTarjeta;
    private String NumeroSeguridad;
    private String VencimientoTarjeta;
    private Float MontoTotal;
    private byte[] Foto1;
    private byte[] Foto2;
    private byte[] Foto3;
    private byte[] Foto4;
    private byte[] FotoFirma;
    private String Generico1;
    private String Generico2;
    private String Generico3;
    private String Generico4;
    private String Generico5;
    private String Generico6;
    private String Generico7;
    private String Generico8;
    private String Generico9;
    private String Generico10;
    private String Generico11;
    private String Generico12;
    private String Generico13;
    private String Generico14;
    private String Generico15;
    private String Generico16;
    private String Generico17;
    private String Generico18;
    private String Generico19;
    private String Generico20;
    private String Generico21;
    private String Generico22;
    private String Generico23;
    private String Generico24;
    private String Generico25;
    private String Generico26;
    private String Generico27;
    private String Generico28;
    private String Generico29;
    private String Generico30;

    // KEEP FIELDS - put your custom fields here
    static Contrato contratoSingleton;
    // KEEP FIELDS END

    public Contrato() {
    }

    public Contrato(Long id) {
        this.id = id;
    }

    public Contrato(Long id, java.util.Date Fecha, String TipoIdentificacion, String Identificacion, String Pasaporte, String Nombre, String Apellido1, String Apellido2, String Email, String Sexo, java.util.Date FechaNacimiento, String TelCasa, String TelCel, String TelCel2, String Fax, String Direccion, String OtrasSenas, String Provincia, String Canton, String Distrito, String TipoTarjeta, String NumeroTarjeta, String NumeroSeguridad, String VencimientoTarjeta, Float MontoTotal, byte[] Foto1, byte[] Foto2, byte[] Foto3, byte[] Foto4, byte[] FotoFirma, String Generico1, String Generico2, String Generico3, String Generico4, String Generico5, String Generico6, String Generico7, String Generico8, String Generico9, String Generico10, String Generico11, String Generico12, String Generico13, String Generico14, String Generico15, String Generico16, String Generico17, String Generico18, String Generico19, String Generico20, String Generico21, String Generico22, String Generico23, String Generico24, String Generico25, String Generico26, String Generico27, String Generico28, String Generico29, String Generico30) {
        this.id = id;
        this.Fecha = Fecha;
        this.TipoIdentificacion = TipoIdentificacion;
        this.Identificacion = Identificacion;
        this.Pasaporte = Pasaporte;
        this.Nombre = Nombre;
        this.Apellido1 = Apellido1;
        this.Apellido2 = Apellido2;
        this.Email = Email;
        this.Sexo = Sexo;
        this.FechaNacimiento = FechaNacimiento;
        this.TelCasa = TelCasa;
        this.TelCel = TelCel;
        this.TelCel2 = TelCel2;
        this.Fax = Fax;
        this.Direccion = Direccion;
        this.OtrasSenas = OtrasSenas;
        this.Provincia = Provincia;
        this.Canton = Canton;
        this.Distrito = Distrito;
        this.TipoTarjeta = TipoTarjeta;
        this.NumeroTarjeta = NumeroTarjeta;
        this.NumeroSeguridad = NumeroSeguridad;
        this.VencimientoTarjeta = VencimientoTarjeta;
        this.MontoTotal = MontoTotal;
        this.Foto1 = Foto1;
        this.Foto2 = Foto2;
        this.Foto3 = Foto3;
        this.Foto4 = Foto4;
        this.FotoFirma = FotoFirma;
        this.Generico1 = Generico1;
        this.Generico2 = Generico2;
        this.Generico3 = Generico3;
        this.Generico4 = Generico4;
        this.Generico5 = Generico5;
        this.Generico6 = Generico6;
        this.Generico7 = Generico7;
        this.Generico8 = Generico8;
        this.Generico9 = Generico9;
        this.Generico10 = Generico10;
        this.Generico11 = Generico11;
        this.Generico12 = Generico12;
        this.Generico13 = Generico13;
        this.Generico14 = Generico14;
        this.Generico15 = Generico15;
        this.Generico16 = Generico16;
        this.Generico17 = Generico17;
        this.Generico18 = Generico18;
        this.Generico19 = Generico19;
        this.Generico20 = Generico20;
        this.Generico21 = Generico21;
        this.Generico22 = Generico22;
        this.Generico23 = Generico23;
        this.Generico24 = Generico24;
        this.Generico25 = Generico25;
        this.Generico26 = Generico26;
        this.Generico27 = Generico27;
        this.Generico28 = Generico28;
        this.Generico29 = Generico29;
        this.Generico30 = Generico30;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getFecha() {
        return Fecha;
    }

    public void setFecha(java.util.Date Fecha) {
        this.Fecha = Fecha;
    }

    public String getTipoIdentificacion() {
        return TipoIdentificacion;
    }

    public void setTipoIdentificacion(String TipoIdentificacion) {
        this.TipoIdentificacion = TipoIdentificacion;
    }

    public String getIdentificacion() {
        return Identificacion;
    }

    public void setIdentificacion(String Identificacion) {
        this.Identificacion = Identificacion;
    }

    public String getPasaporte() {
        return Pasaporte;
    }

    public void setPasaporte(String Pasaporte) {
        this.Pasaporte = Pasaporte;
    }

    /** Not-null value. */
    public String getNombre() {
        return Nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    /** Not-null value. */
    public String getApellido1() {
        return Apellido1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApellido1(String Apellido1) {
        this.Apellido1 = Apellido1;
    }

    public String getApellido2() {
        return Apellido2;
    }

    public void setApellido2(String Apellido2) {
        this.Apellido2 = Apellido2;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    /** Not-null value. */
    public String getSexo() {
        return Sexo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSexo(String Sexo) {
        this.Sexo = Sexo;
    }

    /** Not-null value. */
    public java.util.Date getFechaNacimiento() {
        return FechaNacimiento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaNacimiento(java.util.Date FechaNacimiento) {
        this.FechaNacimiento = FechaNacimiento;
    }

    public String getTelCasa() {
        return TelCasa;
    }

    public void setTelCasa(String TelCasa) {
        this.TelCasa = TelCasa;
    }

    public String getTelCel() {
        return TelCel;
    }

    public void setTelCel(String TelCel) {
        this.TelCel = TelCel;
    }

    public String getTelCel2() {
        return TelCel2;
    }

    public void setTelCel2(String TelCel2) {
        this.TelCel2 = TelCel2;
    }

    public String getFax() {
        return Fax;
    }

    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    /** Not-null value. */
    public String getDireccion() {
        return Direccion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }

    public String getOtrasSenas() {
        return OtrasSenas;
    }

    public void setOtrasSenas(String OtrasSenas) {
        this.OtrasSenas = OtrasSenas;
    }

    public String getProvincia() {
        return Provincia;
    }

    public void setProvincia(String Provincia) {
        this.Provincia = Provincia;
    }

    public String getCanton() {
        return Canton;
    }

    public void setCanton(String Canton) {
        this.Canton = Canton;
    }

    public String getDistrito() {
        return Distrito;
    }

    public void setDistrito(String Distrito) {
        this.Distrito = Distrito;
    }

    public String getTipoTarjeta() {
        return TipoTarjeta;
    }

    public void setTipoTarjeta(String TipoTarjeta) {
        this.TipoTarjeta = TipoTarjeta;
    }

    public String getNumeroTarjeta() {
        return NumeroTarjeta;
    }

    public void setNumeroTarjeta(String NumeroTarjeta) {
        this.NumeroTarjeta = NumeroTarjeta;
    }

    public String getNumeroSeguridad() {
        return NumeroSeguridad;
    }

    public void setNumeroSeguridad(String NumeroSeguridad) {
        this.NumeroSeguridad = NumeroSeguridad;
    }

    public String getVencimientoTarjeta() {
        return VencimientoTarjeta;
    }

    public void setVencimientoTarjeta(String VencimientoTarjeta) {
        this.VencimientoTarjeta = VencimientoTarjeta;
    }

    public Float getMontoTotal() {
        return MontoTotal;
    }

    public void setMontoTotal(Float MontoTotal) {
        this.MontoTotal = MontoTotal;
    }

    public byte[] getFoto1() {
        return Foto1;
    }

    public void setFoto1(byte[] Foto1) {
        this.Foto1 = Foto1;
    }

    public byte[] getFoto2() {
        return Foto2;
    }

    public void setFoto2(byte[] Foto2) {
        this.Foto2 = Foto2;
    }

    public byte[] getFoto3() {
        return Foto3;
    }

    public void setFoto3(byte[] Foto3) {
        this.Foto3 = Foto3;
    }

    public byte[] getFoto4() {
        return Foto4;
    }

    public void setFoto4(byte[] Foto4) {
        this.Foto4 = Foto4;
    }

    public byte[] getFotoFirma() {
        return FotoFirma;
    }

    public void setFotoFirma(byte[] FotoFirma) {
        this.FotoFirma = FotoFirma;
    }

    public String getGenerico1() {
        return Generico1;
    }

    public void setGenerico1(String Generico1) {
        this.Generico1 = Generico1;
    }

    public String getGenerico2() {
        return Generico2;
    }

    public void setGenerico2(String Generico2) {
        this.Generico2 = Generico2;
    }

    public String getGenerico3() {
        return Generico3;
    }

    public void setGenerico3(String Generico3) {
        this.Generico3 = Generico3;
    }

    public String getGenerico4() {
        return Generico4;
    }

    public void setGenerico4(String Generico4) {
        this.Generico4 = Generico4;
    }

    public String getGenerico5() {
        return Generico5;
    }

    public void setGenerico5(String Generico5) {
        this.Generico5 = Generico5;
    }

    public String getGenerico6() {
        return Generico6;
    }

    public void setGenerico6(String Generico6) {
        this.Generico6 = Generico6;
    }

    public String getGenerico7() {
        return Generico7;
    }

    public void setGenerico7(String Generico7) {
        this.Generico7 = Generico7;
    }

    public String getGenerico8() {
        return Generico8;
    }

    public void setGenerico8(String Generico8) {
        this.Generico8 = Generico8;
    }

    public String getGenerico9() {
        return Generico9;
    }

    public void setGenerico9(String Generico9) {
        this.Generico9 = Generico9;
    }

    public String getGenerico10() {
        return Generico10;
    }

    public void setGenerico10(String Generico10) {
        this.Generico10 = Generico10;
    }

    public String getGenerico11() {
        return Generico11;
    }

    public void setGenerico11(String Generico11) {
        this.Generico11 = Generico11;
    }

    public String getGenerico12() {
        return Generico12;
    }

    public void setGenerico12(String Generico12) {
        this.Generico12 = Generico12;
    }

    public String getGenerico13() {
        return Generico13;
    }

    public void setGenerico13(String Generico13) {
        this.Generico13 = Generico13;
    }

    public String getGenerico14() {
        return Generico14;
    }

    public void setGenerico14(String Generico14) {
        this.Generico14 = Generico14;
    }

    public String getGenerico15() {
        return Generico15;
    }

    public void setGenerico15(String Generico15) {
        this.Generico15 = Generico15;
    }

    public String getGenerico16() {
        return Generico16;
    }

    public void setGenerico16(String Generico16) {
        this.Generico16 = Generico16;
    }

    public String getGenerico17() {
        return Generico17;
    }

    public void setGenerico17(String Generico17) {
        this.Generico17 = Generico17;
    }

    public String getGenerico18() {
        return Generico18;
    }

    public void setGenerico18(String Generico18) {
        this.Generico18 = Generico18;
    }

    public String getGenerico19() {
        return Generico19;
    }

    public void setGenerico19(String Generico19) {
        this.Generico19 = Generico19;
    }

    public String getGenerico20() {
        return Generico20;
    }

    public void setGenerico20(String Generico20) {
        this.Generico20 = Generico20;
    }

    public String getGenerico21() {
        return Generico21;
    }

    public void setGenerico21(String Generico21) {
        this.Generico21 = Generico21;
    }

    public String getGenerico22() {
        return Generico22;
    }

    public void setGenerico22(String Generico22) {
        this.Generico22 = Generico22;
    }

    public String getGenerico23() {
        return Generico23;
    }

    public void setGenerico23(String Generico23) {
        this.Generico23 = Generico23;
    }

    public String getGenerico24() {
        return Generico24;
    }

    public void setGenerico24(String Generico24) {
        this.Generico24 = Generico24;
    }

    public String getGenerico25() {
        return Generico25;
    }

    public void setGenerico25(String Generico25) {
        this.Generico25 = Generico25;
    }

    public String getGenerico26() {
        return Generico26;
    }

    public void setGenerico26(String Generico26) {
        this.Generico26 = Generico26;
    }

    public String getGenerico27() {
        return Generico27;
    }

    public void setGenerico27(String Generico27) {
        this.Generico27 = Generico27;
    }

    public String getGenerico28() {
        return Generico28;
    }

    public void setGenerico28(String Generico28) {
        this.Generico28 = Generico28;
    }

    public String getGenerico29() {
        return Generico29;
    }

    public void setGenerico29(String Generico29) {
        this.Generico29 = Generico29;
    }

    public String getGenerico30() {
        return Generico30;
    }

    public void setGenerico30(String Generico30) {
        this.Generico30 = Generico30;
    }

    // KEEP METHODS - put your custom methods here
    public static Contrato getContratoSingleton() {
        if(contratoSingleton == null){
            contratoSingleton = new Contrato();
        }
        return contratoSingleton;
    }

    @Override
    public String toString() {
        return "Contrato{" +
                "id=" + id +
                ", ConFecha=" + Fecha +
                '}';
    }
    // KEEP METHODS END

}
