package cr.co.sea.seaforms.Model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FORMULARIO".
 */
public class Formulario {

    private Long id;
    private String Form_nombre;
    private String Form_valor;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Formulario() {
    }

    public Formulario(Long id) {
        this.id = id;
    }

    public Formulario(Long id, String Form_nombre, String Form_valor) {
        this.id = id;
        this.Form_nombre = Form_nombre;
        this.Form_valor = Form_valor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getForm_nombre() {
        return Form_nombre;
    }

    public void setForm_nombre(String Form_nombre) {
        this.Form_nombre = Form_nombre;
    }

    public String getForm_valor() {
        return Form_valor;
    }

    public void setForm_valor(String Form_valor) {
        this.Form_valor = Form_valor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
